language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=align-it
  - PACKAGE=avalon
  - PACKAGE=chargemol
  - PACKAGE=checkmol
  - PACKAGE=chemistry-development-kit
  - PACKAGE=cluster
  - PACKAGE=critic2
  - PACKAGE=filter-it
  - PACKAGE=gocr
  - PACKAGE=helium
  - PACKAGE=inchi
  - PACKAGE=jcompoundmapper
  - PACKAGE=opsin
  - PACKAGE=osra
  - PACKAGE=shape-it
  - PACKAGE=smartcyp
  - PACKAGE=strip-it
  - PACKAGE=subset
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE $OPTIONS
  - brew test $PACKAGE
